[pytest]
testpaths = tests
python_files = test_*.py
addopts = -v

log_cli = false
log_cli_level = DEBUG
log_cli_format = [%(levelname)s] %(asctime)s - %(name)s - %(message)s
log_cli_date_format = %H:%M:%S
